spring.application.name=dio-projeto-final-bootcamp-santander-java-ai-backend-2026

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.response-format.type=TEXT